[focusPrevious]
key = "k"
modifiers = [ "super" ]

[focusNext]
key = "j"
modifiers = [ "super" ]

[toggleFullscreen]
key = "f"
modifiers = [ "super" ]

[destroySelectedWindow]
key = "q"
modifiers = [ "super", "shift" ]
